// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5tZcJYHA8X1hgAD7jYM3-FCLQ7h7-XuU',
    appId: '1:169081098691:web:357eb089ce8d097c0fad76',
    messagingSenderId: '169081098691',
    projectId: 'todo-cd175',
    authDomain: 'todo-cd175.firebaseapp.com',
    storageBucket: 'todo-cd175.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-kzFjD9_6rs3TaoYdUF5w7WSDOZ413vE',
    appId: '1:169081098691:android:a2d48b5cbdb56ca60fad76',
    messagingSenderId: '169081098691',
    projectId: 'todo-cd175',
    storageBucket: 'todo-cd175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5NnxrMu4UJOX8UK7mMPnKrz6d-cpuEJQ',
    appId: '1:169081098691:ios:19d35363585562b80fad76',
    messagingSenderId: '169081098691',
    projectId: 'todo-cd175',
    storageBucket: 'todo-cd175.firebasestorage.app',
    iosBundleId: 'com.example.cubitLabDesarrollo4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5NnxrMu4UJOX8UK7mMPnKrz6d-cpuEJQ',
    appId: '1:169081098691:ios:19d35363585562b80fad76',
    messagingSenderId: '169081098691',
    projectId: 'todo-cd175',
    storageBucket: 'todo-cd175.firebasestorage.app',
    iosBundleId: 'com.example.cubitLabDesarrollo4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5tZcJYHA8X1hgAD7jYM3-FCLQ7h7-XuU',
    appId: '1:169081098691:web:632f0adb8b4502c80fad76',
    messagingSenderId: '169081098691',
    projectId: 'todo-cd175',
    authDomain: 'todo-cd175.firebaseapp.com',
    storageBucket: 'todo-cd175.firebasestorage.app',
  );
}
